CREATE TABLE Cookies (
    UserID INT AUTO_INCREMENT,
    CFID VARCHAR(255) NOT NULL UNIQUE,
    CFTOKEN VARCHAR(255) NOT NULL UNIQUE,
    SESSIONID VARCHAR(255) NOT NULL UNIQUE,
    SESSIONTOKEN VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
)
CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    userKey VARCHAR(255) NOT NULL UNIQUE,    
)

--@block
SELECT * FROM Cookies
